# Generated by Django 5.2.4 on 2025-07-31 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessWithoutFix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_type",
                    models.CharField(db_index=True, editable=False, max_length=100),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Businesses Without Fix",
            },
        ),
        migrations.CreateModel(
            name="BusinessWithFix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_type",
                    models.CharField(db_index=True, editable=False, max_length=100),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name_plural": "Businesses With Fix",
            },
        ),
        migrations.CreateModel(
            name="BusinessExtensionWithoutFix",
            fields=[
                (
                    "businesswithoutfix_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="test_app.businesswithoutfix",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name_plural": "Business Extensions Without Fix",
            },
            bases=("test_app.businesswithoutfix",),
        ),
        migrations.CreateModel(
            name="BusinessExtensionWithFix",
            fields=[],
            options={
                "verbose_name_plural": "Business Extensions With Fix",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("test_app.businesswithfix",),
        ),
    ]
